version: "3.9"

services:
  database:
    image: mariadb:10.5
    container_name: cloudcart-db

    environment:
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_DATABASE: cloudcart
      MARIADB_USER: cloudcart
      MARIADB_PASSWORD: CloudCart@123

    volumes:
      - db_data:/var/lib/mysql
      - ../app/database/init.sql:/docker-entrypoint-initdb.d/init.sql


  backend:
    build:
      context: ../app/backend
      dockerfile: Dockerfile
    
    container_name: cloudcart-backend

    ports:
      - "5000:5000"

    depends_on:
      - database

volumes:
  db_data:
     
