apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloudcart-db

spec:
  replicas: 1

  selector:
    matchLabels:
      app: cloudcart-db

  template:
    metadata:
      labels:
        app: cloudcart-db

    spec:
      containers:
      - name: mariadb

        image: mariadb:10.5

        ports:
        - containerPort: 3306

        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudcart-db-mariadb-secret
              key: MARIADB_ROOT_PASSWORD

        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: cloudcart-db-config
              key: MARIADB_DATABASE

        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: cloudcart-db-mariadb-secret
              key: MARIADB_USER

        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudcart-db-mariadb-secret
              key: MARIADB_PASSWORD

        volumeMounts:

        - name: db-storage
          mountPath: /var/lib/mysql

        - name: db-init
          mountPath: /docker-entrypoint-initdb.d

      volumes:

      - name: db-storage
        persistentVolumeClaim:
          claimName: cloudcart-db-pvc

      - name: db-init
        configMap:
          name: cloudcart-db-init
