apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloudcart-db

spec:
  replicas: 1

  selector:
    matchLabels:
      app: cloudcart-db

  template:
    metadata:
      labels:
        app: cloudcart-db

    spec:
      containers:
      - name: mariadb

        image: mariadb:10.5

        ports:
        - containerPort: 3306

        env:
        - name: MARIADB_ROOT_PASSWORD
          value: root123

        - name: MARIADB_DATABASE
          value: cloudcart

        - name: MARIADB_USER
          value: cloudcart

        - name: MARIADB_PASSWORD
          value: CloudCart@123

        volumeMounts:
        - name: db-init
          mountPath: /docker-entrypoint-initdb.d

      volumes:
      - name: db-init
        configMap:
          name: cloudcart-db-init
